/**
 * Setup Command
 * Handles: dev-agent setup
 * Walks the user through configuring API keys.
 * Stores them in ~/.dev-agent/.env so they persist globally.
 */

import readline from "node:readline/promises";
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { homedir } from "node:os";
import chalk from "chalk";

const CONFIG_DIR = resolve(homedir(), ".dev-agent");
const ENV_FILE = resolve(CONFIG_DIR, ".env");

/**
 * Execute the setup command.
 */
export async function setupCommand() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log(chalk.cyan("\n  🔧 Dev-Agent Setup\n"));
  console.log(chalk.gray(`  Config will be saved to: ${ENV_FILE}\n`));

  // Load existing values if any
  let existing = {};
  if (existsSync(ENV_FILE)) {
    const content = readFileSync(ENV_FILE, "utf-8");
    for (const line of content.split("\n")) {
      const match = line.match(/^(\w+)=(.*)$/);
      if (match) existing[match[1]] = match[2];
    }
    console.log(chalk.gray("  Found existing config. Press Enter to keep current values.\n"));
  }

  const groqKey = await rl.question(
    chalk.white(`  GROQ_API_KEY ${existing.GROQ_API_KEY ? chalk.gray(`[${mask(existing.GROQ_API_KEY)}]`) : ""}: `)
  );

  const tavilyKey = await rl.question(
    chalk.white(`  TAVILY_API_KEY ${existing.TAVILY_API_KEY ? chalk.gray(`[${mask(existing.TAVILY_API_KEY)}]`) : chalk.gray("(optional)")}: `)
  );

  rl.close();

  // Merge with existing
  const finalGroq = groqKey.trim() || existing.GROQ_API_KEY || "";
  const finalTavily = tavilyKey.trim() || existing.TAVILY_API_KEY || "";

  if (!finalGroq) {
    console.log(chalk.yellow("\n  ⚠ No GROQ_API_KEY provided. Dev-Agent won't work without it."));
    console.log(chalk.gray("  Get one at: https://console.groq.com/keys\n"));
    return;
  }

  // Write config
  mkdirSync(CONFIG_DIR, { recursive: true });

  const envContent = [
    `# Dev-Agent Configuration`,
    `# Generated by: dev-agent setup`,
    ``,
    `GROQ_API_KEY=${finalGroq}`,
    finalTavily ? `TAVILY_API_KEY=${finalTavily}` : `# TAVILY_API_KEY=your_key_here`,
    ``,
  ].join("\n");

  writeFileSync(ENV_FILE, envContent, "utf-8");

  console.log(chalk.green(`\n  ✔ Config saved to ${ENV_FILE}`));
  console.log(chalk.gray("  You're all set! Try: dev-agent ask \"What is a closure?\"\n"));
}

/**
 * Mask an API key for display (show first 6 and last 4 chars).
 * @param {string} key
 * @returns {string}
 */
function mask(key) {
  if (!key || key.length < 12) return "****";
  return key.slice(0, 6) + "..." + key.slice(-4);
}
